import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CScrum Poker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center min-h-screen py-2">
        <h1 className="text-6xl font-bold">
          Welcome to Poker
        </h1>
      </main>
    </div>
  );
}
